
export type Product = {
  id: string;
  name: string;
  description: string;
  priceINR: number;
  priceUSD: number;
  imagePlaceholder: string; // URL for placeholder image
  aiHint: string; // Hint for AI image generation if needed
  category: 'Equipment' | 'Apparel' | 'Nutrition' | 'Wearables' | 'Accessories';
  slug: string; // for URL generation
};

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Smart Hydration Bottle',
    description: 'Tracks your water intake and glows to remind you to drink. Syncs with the Fitnity AI app.',
    priceINR: 2499,
    priceUSD: 30,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'smart water bottle futuristic',
    category: 'Accessories',
    slug: 'smart-hydration-bottle',
  },
  {
    id: 'prod_002',
    name: 'AI-Optimized Yoga Mat',
    description: 'Premium non-slip yoga mat with alignment guides. Pairs with Fitnity AI form analysis for yoga.',
    priceINR: 3999,
    priceUSD: 49,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'yoga mat modern tech',
    category: 'Equipment',
    slug: 'ai-yoga-mat',
  },
  {
    id: 'prod_003',
    name: 'Performance T-Shirt',
    description: 'Lightweight, breathable fabric with moisture-wicking technology. Designed for intense workouts.',
    priceINR: 1299,
    priceUSD: 18,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'performance t-shirt fitness',
    category: 'Apparel',
    slug: 'performance-t-shirt',
  },
  {
    id: 'prod_004',
    name: 'Fitnity AI Whey Protein',
    description: 'High-quality whey protein isolate, optimized for muscle recovery. Recommended by Fitnity AI Nutrition.',
    priceINR: 2999,
    priceUSD: 38,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'protein powder modern container',
    category: 'Nutrition',
    slug: 'fitnity-whey-protein',
  },
  {
    id: 'prod_005',
    name: 'Advanced Fitness Tracker',
    description: 'Monitors heart rate, sleep, SpO2, and integrates seamlessly with your Fitnity AI dashboard.',
    priceINR: 7999,
    priceUSD: 99,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'fitness tracker sleek display',
    category: 'Wearables',
    slug: 'advanced-fitness-tracker',
  },
  {
    id: 'prod_006',
    name: 'Adjustable Dumbbell Set',
    description: 'Space-saving adjustable dumbbells, perfect for home workouts. Ideal for Fitnity AI strength plans.',
    priceINR: 9999,
    priceUSD: 125,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'adjustable dumbbell set modern',
    category: 'Equipment',
    slug: 'adjustable-dumbbell-set',
  },
  {
    id: 'prod_007',
    name: 'Resistance Bands Set (Set of 5)',
    description: 'Versatile latex bands for strength training, stretching, and rehabilitation. Multiple resistance levels.',
    priceINR: 1499,
    priceUSD: 20,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'resistance bands colorful',
    category: 'Equipment',
    slug: 'resistance-bands-set',
  },
  {
    id: 'prod_008',
    name: 'Smart Jump Rope',
    description: 'Digital jump rope that tracks skips, time, and calories burned. Connects to fitness apps.',
    priceINR: 2999,
    priceUSD: 38,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'smart jump rope digital',
    category: 'Equipment',
    slug: 'smart-jump-rope',
  },
  {
    id: 'prod_009',
    name: 'Performance Leggings',
    description: 'High-waisted, squat-proof leggings with moisture-wicking fabric and a comfortable four-way stretch.',
    priceINR: 2199,
    priceUSD: 28,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'fitness leggings stylish',
    category: 'Apparel',
    slug: 'performance-leggings',
  },
  {
    id: 'prod_010',
    name: 'Fitnity AI Plant Protein',
    description: 'Premium plant-based protein blend (pea, brown rice) for muscle growth and recovery. Vegan-friendly.',
    priceINR: 3299,
    priceUSD: 42,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'plant protein modern container',
    category: 'Nutrition',
    slug: 'fitnity-plant-protein',
  },
  {
    id: 'prod_011',
    name: 'Smart Body Composition Scale',
    description: 'Measures weight, BMI, body fat, muscle mass, and more. Syncs data to the Fitnity AI app.',
    priceINR: 4999,
    priceUSD: 65,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'smart scale sleek',
    category: 'Wearables',
    slug: 'smart-body-scale',
  },
  {
    id: 'prod_012',
    name: 'Premium Foam Roller',
    description: 'High-density EVA foam roller for muscle soreness relief, improving flexibility and circulation.',
    priceINR: 1799,
    priceUSD: 24,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'foam roller fitness',
    category: 'Equipment',
    slug: 'premium-foam-roller',
  },
  {
    id: 'prod_013',
    name: 'Breathable Training Tank',
    description: 'Ultra-lightweight and breathable tank top, perfect for high-intensity workouts. Quick-drying material.',
    priceINR: 999,
    priceUSD: 14,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'training tank top minimalist',
    category: 'Apparel',
    slug: 'breathable-training-tank',
  },
  {
    id: 'prod_014',
    name: 'BCAA Amino Acids',
    description: 'Essential Branch-Chain Amino Acids to support muscle recovery, reduce fatigue, and promote lean muscle growth.',
    priceINR: 1899,
    priceUSD: 25,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'bcaa supplement container',
    category: 'Nutrition',
    slug: 'bcaa-amino-acids',
  },
  {
    id: 'prod_015',
    name: 'Compact Gym Bag',
    description: 'Durable and water-resistant gym bag with multiple compartments, including a shoe tunnel.',
    priceINR: 2299,
    priceUSD: 29,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'gym bag modern',
    category: 'Accessories',
    slug: 'compact-gym-bag',
  },
  {
    id: 'prod_016',
    name: 'Ergonomic Shaker Bottle',
    description: 'Leak-proof shaker bottle with a mixing ball for smooth protein shakes and supplements. BPA-free.',
    priceINR: 799,
    priceUSD: 10,
    imagePlaceholder: 'https://placehold.co/300x300.png',
    aiHint: 'shaker bottle sleek',
    category: 'Accessories',
    slug: 'ergonomic-shaker-bottle',
  },
];
